services:
  keycloak:
    # https://www.keycloak.org/server/containers
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    command: start-dev
    restart: always
    ports:
      - "9080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
